#!/bin/bash

## This is the script to bootstrap WireGuard Server in Docker on AWS EC2 Ubuntu instance ## 

# launch updates of Ubuntu and installed software
sudo apt update && apt upgrade -y

# install AWS-CLI
sudo apt install awscli -y

# intall Docker
sudo curl -sSL https://get.docker.com | sh

# setup user for Docker
sudo usermod -aG docker $(whoami)

# setup environment variables
export META_INST_HOSTNAME=`curl http://169.254.169.254/latest/meta-data/public-hostname`
export META_DATA_REGION=`curl http://169.254.169.254/latest/meta-data/placement/region`
export META_ADMIN_PASSWORD=`aws ssm get-parameters --name WGPassword --region $META_DATA_REGION --with-decryption --output text --query Parameters[].Value`

# run docker image with WireGuard
docker run -d \
  --name=wg-easy \
  -e WG_HOST=$META_INST_HOSTNAME \
  -e PASSWORD=$META_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy

